name: 步多多

on:
  workflow_dispatch:
  schedule:
     - cron: '7 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/pizile/ZY.git ~/ZY
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/ZY
          git checkout mian
          npm install
      - name: '运行 【步多多】'
        run: |
          cd ~/ZY
          node Task/ddayd.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}