# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FL2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12,23 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: FL2
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Joinmogul/ziye12_JavaScript.git ~/ziye12_JavaScript
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/ziye12_JavaScript
          npm install
      - name: '运行 【返利网2】'
        run: |
          cd ~/ziye12_JavaScript
          node Task/flw.js
        env:
          FL_flwURL: ${{ secrets.FL_flwURL2 }}
          FL_flwHEADER: ${{ secrets.FL_flwHEADER2 }}		
          FL_flwspBODY: ${{ secrets.FL_flwspBODY2 }}	
          FL_flwqwBODY: ${{ secrets.FL_flwqwBODY2 }}        
          FL_CASH: ${{ secrets.FL_CASH2 }}//天天领现金提现
          FL_DHCASH: ${{ secrets.FL_DHCASH2 }}//签到活动兑换
