name: 书旗
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          git clone https://github.com/pizile/ZY.git ~/ZY
          cd ~/ZY
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '【书旗小说】'
        run: |
          cd ~/ZY
          node Task/sqxs.js
